# Classifier configs of both folds.
# The first entry is used for the even event numbers (N%2==0) and
# the second for the odd event numbers (N%2==1)
# NOTE: To be indepedent, the classifier trained on fold 1 needs to be
# booked first and vice versa.
classifiers:
    - ml/et/fold1_keras_model_smhtt.h5
    - ml/et/fold0_keras_model_smhtt.h5

preprocessing:
    - ml/et/fold1_keras_preprocessing_smhtt.pickle
    - ml/et/fold0_keras_preprocessing_smhtt.pickle

# Prefix of new branches with method's responses
branch_prefix: "et_keras50_"
