# Training datasets for different folds
datasets:
    - ml/et/fold0_et_training_dataset.root
    - ml/et/fold1_et_training_dataset.root

# Base path for all output files
output_path: ml/et

# Define classes based on tree names in dataset file
classes:
    - htt
    - ztt
    - zll
    - w
    - tt
    - qcd

# Set class weights
class_weights:
    htt: 50.0
    ztt: 1.0
    zll: 1.0
    w: 1.0
    tt: 1.0
    qcd: 1.0

# Define global scale factor, which is multiplied to all event weights
global_weight_scale: 1.0

# Set event weight variable
event_weights: training_weight

# Define list of variables to be used for training
variables:
#   - m_sv
    - pt_1
    - pt_2
    - jpt_1
    - jcsv_2
    - jm_1
    - bpt_1
    - bpt_2
    - beta_1
    - beta_2
    - bphi_1
    - bphi_2
    - bcsv_1
    - bcsv_2
    - njets
    - nbtag
    - mt_1
    - mt_2
    - ptvis
    - pt_tt
    - mjj
    - m_vis
    - dijetpt
    - met

# Split of dataset in training and validation (in TMVA called training and testing)
train_test_split: 0.75

# Define preprocessing
preprocessing: standard_scaler

# Define the model parameter
model:
    name: smhtt
    batch_size: 10000
    epochs: 10000
    early_stopping: 10
    save_best_only: true
