# Classifier configs of both folds.
# The first entry is used for the even event numbers (N%2==0) and
# the second for the odd event numbers (N%2==1)
# NOTE: To be indepedent, the classifier trained on fold 1 needs to be
# booked first and vice versa.
classifiers:
    - ml/mt/fold1_training/weights/TMVAMulticlass_PyKeras_fold1.weights.xml
    - ml/mt/fold0_training/weights/TMVAMulticlass_PyKeras_fold0.weights.xml

# Prefix of new branches with method's responses
branch_prefix: "mt_mva_"
