# Classifier configs of both folds.
# The first entry is used for the even event numbers (N%2==0) and
# the second for the odd event numbers (N%2==1)
# NOTE: To be indepedent, the classifier trained on fold 1 needs to be
# booked first and vice versa.
classifiers:
    - ml/mt/fold1_keras_model.h5
    - ml/mt/fold0_keras_model.h5

preprocessing:
    - ml/mt/fold1_keras_preprocessing.pickle
    - ml/mt/fold0_keras_preprocessing.pickle

# Branch prefix
branch_prefix: mt_

# Output directory
output_directory: /storage/c/wunsch/Artus_2018-02-25/mt_keras_1
